### PR TITLE
fix the import location for the .css file

### PR DESCRIPTION
**Pull request by k4b7**

### CODE REVIEW

**Comment by HosseinAgha** [comment]
Thank you @kevinbarabash, I really miss working on KaTeX. 😊

**Comment by k4b7** [comment]
Thanks for making this plugin.  I'm working on integrating it into khanacademy.org.  I'm not sure when that'll get deployed though.  I was thinking that we should add a link to `persian-katex-plugin` from https://katex.org/docs/libs.html.

**Comment by HosseinAgha** [comment]
Yes, That would be awesome. I remember we talked about it before but plugin system had not been merged then. We are using KaTeX and this plugin on production projects for more than a year now and I think It is stable enough.

**Comment by k4b7** [comment]
Cool!  What projects are you using it for?

**Comment by HosseinAgha** [comment]
Lernito is our project focused on formative assessment. Its database contains more than 180K questions. We also plan to use it in an awesome Digital Publishing project 😃.  
We've successfully rendered almost every type of equation using KaTeX in client and server. from super complex Chemistry equations to advanced Mathematics.  
Lernito is mostly used in Persian speaking countries for 6th grade through 12th. But we recently released a beta version for Arabic and English. Interesting thing is that we didn't even need to reload KaTeX when changing language as this plugin is none destructive and only effects Persian and Arabic glyphs. So you practically can add this plugin's code and fonts to KaTeX (considering the bundle size) if you needed permanent Persian and Arabic support.

**Pull request merged**
